### ISSUE TITLE
Some dependence libraries deprecated on Android

### ISSUE THREAD

**Issue by rock77217** [monero-ecosystem/monero-java#24]
Recently I implement this into an Android device.

I found out some dependence libraries are be deprecated on Android.
That cause this library couldn't work fine unless change dependence libraries.
eg. org.apache.commons.codec.binary.Hex and org.apache.httpcomponents.httpclient

Has any chance to change the dependence?

**Comment by woodser** [comment]
Thanks for reporting this issue.  I updated to HttpClient 5 on master which should resolve the issue (new release forthcoming).  Please let me know if you see any other issues.

**Comment by rock77217** [comment]
Thanks for your reply.
The other problem is the encodeHexString in MoneroUtils also deprecated on Android.
#25

**Comment by rock77217** [comment]
Thanks for your help.
I've been checked the release version and it works.
