### ISSUE TITLE
Failed to submit signed tx: transaction was rejected by daemon

### ISSUE THREAD

**Issue by rock77217** [monero-ecosystem/monero-java#26]
Hi, It's me again.

I meet an exception as the title when I send signed tx via submitTxs.
But it's normal when I using relayTx to send the transaction.

Has any idea how I can fix it?

**Comment by woodser** [comment]
`MoneroWallet.submitTxs()` is to be used with signed txs from view-only wallets.

It requires the view-only wallet to be set up in a specific way.  Here's a test which shows setting up a view-only wallet and submitting a signed tx which works for me: https://github.com/monero-ecosystem/monero-java/blob/633398fe7dbf70773f29c9c8b6f19705c46104c9/src/test/java/test/TestMoneroWalletCommon.java#L2128

**Comment by rock77217** [comment]
Yes...
I missed updating the key images.
Thanks for your help.
