### ISSUE TITLE
how to offline generate address  by privatekey or publickey? and how to offline sign?

### ISSUE THREAD

**Issue by lilaizhencn** [monero-ecosystem/monero-java#27]
how to offline generate address  by privatekey or publickey? and how to offline sign?

**Comment by woodser** [comment]
Please see [this documentation](https://github.com/monero-ecosystem/monero-javascript/blob/master/docs/developer_guide/view_only_offline.md) on using view-only and offline wallets to sign transactions offline.

One can get the public addresses of a wallet by importing the mnemonic into a keys-only wallet or disconnected WebAssembly wallet:

```
// keys-only wallet for basic key management
let keysOnlyWallet = await monerojs.createWalletKeys({
  networkType: "stagenet",
  language: "English",
  mnemonic: "darted oatmeal toenail launching frown empty..."
});

// unconnected WebAssembly wallet
let offlineWallet = await monerojs.createWalletWasm({
  path: "my_offline_wallet",
  networkType: "stagenet",
  mnemonic: "spying swept ashtray going hence jester swagger cease spying unusual..."
});
```

**Comment by woodser** [comment]
Please see [this test](https://github.com/monero-ecosystem/monero-java/blob/e9265205474b104ec88a53278086b35209819b5a/src/test/java/test/TestMoneroWalletCommon.java#L2147) which demonstrates using view-only and offline wallets to sign transactions offline.

Also [this documentation](https://github.com/monero-ecosystem/monero-javascript/blob/master/docs/developer_guide/view_only_offline.md) (for the JavaScript library) may be a helpful reference.

One can get the public addresses of a wallet by importing the mnemonic to a JNI or RPC wallet:

```
// RPC wallet
MoneroWalletRpc walletRpc = new MoneroWalletRpc("http://localhost:38083", "rpc_user", "abc123");
walletRpc.createWallet(new MoneroWalletConfig()
        .setPath("mywallet")
        .setPassword("supersecretpassword123")
        .setNetworkType(MoneroNetworkType.STAGENET)
        .setMnemonic("hefty value scenic..."));
String address = walletRpc.getPrimaryAddress();

// JNI wallet
MoneroWalletJni walletJni = MoneroWalletJni.createWallet(new MoneroWalletConfig()
        .setPath("mywallet") // in-memory if not given
        .setPassword("supersecretpassword123")
        .setNetworkType(MoneroNetworkType.STAGENET)
        .setMnemonic("hefty value scenic..."));
address = walletJni.getPrimaryAddress();
```
