### ISSUE TITLE
Monero Wallet RPC: createSubaddress returns same value (on linux)

### ISSUE THREAD

**Issue by wolfomat** [monero-ecosystem/monero-java#29]
Hello there,

i am not sure if it's a problem of this library.
First of all, i've tried monero version v0.17.0.1 and v0.17.1.1
Magically, when i call the WalletRPC on a windows machine, i'll retrieve a new value each time i call createSubaddress(accIdx).
Using the same code on a linux machine (ubuntu/debian with openjdk) it returns each time the first address which have been generated through code.

I'm starting the wallet-rpc on both achines as follows

Windows:
`
monero-wallet-rpc.exe --wallet-dir D:\00_disk_e\coins\monero-wallet\testwallet --rpc-bind-port 4711 --prompt-for-password --rpc-login admin:password`

Linux:
`./monero-wallet-rpc --wallet-dir /media/shopsrv/42ECF9B9ECF9A777/monero-wallet/testwallet2 --rpc-bind-port 4711 --prompt-for-password --rpc-login admin:password`

Of course, the rpc-login is just for testing at the moment.

My call code calls are as follows:

```
final MoneroWalletRpc walletRpc = new MoneroWalletRpc(url, walletConfig.getWalletConfig().getUsername(), walletConfig.getWalletConfig().getPassword());
walletRpc.openWallet(walletConfig.getWalletConfig().getWUsername(),    
walletConfig.getWalletConfig().getWPassword());
final String primaryAddress = walletRpc.getPrimaryAddress();
final MoneroSubaddress moneroSubaddress = walletRpc.getAddressIndex(primaryAddress);
newMoneroAdress = walletRpc.createSubaddress(moneroSubaddress.getAccountIndex());
```

all you see at the getters are simple data-objects containing the information and such.
Do you have an idea or hint where there's a difference on two Operating Systems? I strongly suspect the monero implemenations, but i am not sure about this. maybe you have an idea?

**Comment by wolfomat** [comment]
okay, seems either a call issue or really library issue.
sometimes it works, sometimes not. I've got it managed, that on my windows machine the wallet addresses are always the same.
however, when i startet the monero-gui, the newly created adress was not within the wallet.

when i pressed "create new address" in the gui, a new address was generated, but just like the address from createSubaddress() method.
after another hit on "create new address" within the gui created simply a new address.

Here's the full-code call, any ideas?

```
		try {
			walletRpc.openWallet(walletConfig.getWalletConfig().getWUsername(), walletConfig.getWalletConfig().getWPassword());
			final String primaryAddress = walletRpc.getPrimaryAddress();
			final MoneroSubaddress moneroSubaddress = walletRpc.getAddressIndex(primaryAddress);
			newMoneroAdress = walletRpc.createSubaddress(moneroSubaddress.getAccountIndex());
			return newMoneroAdress == null ? null : newMoneroAdress.getAddress();
		} finally {
			if (!walletRpc.isClosed()) {
				walletRpc.close();
			}
		}
	}
```

**Comment by woodser** [comment]
This is sounding like a discrepancy with monero-wallet-rpc as the library should be making RPC calls the same way on both platforms.  To confirm, you could log and compare the RPC requests and responses to ensure they're identical.  This can be done by uncommenting the `System.out.println()` statements in MoneroRpcConnection.java (needs proper logging config :/).

Note that unused created subaddresses will not carry over when restoring a wallet from mnemonic, but they should be saved to wallet files.

**Comment by wolfomat** [comment]
somehow i managed to provoke this on windows, too. which is "nice".
i'll try the sysouts or just inject the log4j logger in there and replace the calls.
let me try this out, i guess there's something i am not doing right.

**Comment by wolfomat** [comment]
soooo, after a while i figured out that i need to call walletRpc.save()
then the address is really persisted on the wallet.
