### ISSUE TITLE
Not able to specify exact unspent outputs to use for a transaction.

### ISSUE THREAD

**Issue by suggalla** [monero-ecosystem/monero-java#40]
Hello, I've recently been using the monero-java library and upon creating a transaction using the `createTx` method I realized we cannot specify our own unspent outputs to spend from. So I'm wondering if there is another way to accomplish this same functionality. I couldn't find anything from poking around the library. Thanks!

**Comment by woodser** [comment]
You can use either the `sweepOutput()` method specifying the key image of the output to spend, or you can use the `createTx()` method specifying a subaddress or account to spend from to restrict the source outputs.

**Comment by suggalla** [comment]
Thanks for the info! Is there anyway to pick multiple UTXOs to spend from as well as set the change output? This is just so we can manage our own UTXO coin selection algorithm.

**Comment by woodser** [comment]
No, this isn't supported in the core Monero software ([monero/monero-project](https://github.com/monero-project/monero)) to my knowledge, which this library is a straight passthrough for.

**Comment by suggalla** [comment]
Appreciate the info, thanks again!
