### ISSUE TITLE
能否提供离线签名的java版,不具备使用jni的条件

### ISSUE THREAD

**Issue by Wbsba** [monero-ecosystem/monero-java#41]
需要离线签名java版

**Comment by woodser** [comment]
> Can you provide a java version of offline signature, which does not meet the conditions for using jni

> Need offline signature java version

You can use monero-wallet-rpc in offline mode to sign transactions offline without JNI, by starting monero-wallet-rpc with `--offline`.

Otherwise JNI is necessary to sign transactions without monero-wallet-rpc.

**Comment by Wbsba** [comment]
> > Can you provide a java version of offline signature, which does not meet the conditions for using jni
> 
> > Need offline signature java version
> 
> You can use monero-wallet-rpc in offline mode to sign transactions offline without JNI, by starting monero-wallet-rpc with `--offline`.
> 
> Otherwise JNI is necessary to sign transactions without monero-wallet-rpc.

或者是否能把签名的过程和签名的方式告诉我,通过monero-wallet-rpc秘钥不还是存储在服务器上吗?我不想这么做
