### ISSUE TITLE
Build problem

### ISSUE THREAD

**Issue by bigBonSlime** [monero-ecosystem/monero-java#60]
Ubuntu 23.04
`
[100%] Built target monero-cpp
-- The C compiler identification is GNU 12.3.0
-- The CXX compiler identification is GNU 12.3.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- MONERO_CPP:/home/user/Desktop/lib/monero-java/external/monero-cpp:/home/user/Desktop/lib/monero-java/external/monero-cpp
CMake Error at CMakeLists.txt:28 (include_directories):
  include_directories given empty-string as include directory.

-- EXTRA_LIBRARIES:
-- Using Boost include dir at /usr/include
-- Found OpenSSL: /usr/lib/x86_64-linux-gnu/libcrypto.so (found version "3.0.8")  
-- Using OpenSSL include dir at /usr/include
-- Configuring incomplete, errors occurred!
See also "/home/user/Desktop/lib/monero-java/build/CMakeFiles/CMakeOutput.log".

`

**Comment by woodser** [comment]
Is there a build error running `make release-static -j<numThreads>` in monero-cpp/external/monero-project, or does it complete successfully?

**Comment by woodser** [comment]
Did you set `JAVA_HOME`? From the instructions: `export JAVA_HOME=/path/to/jdk`

**Comment by bigBonSlime** [comment]
This solved the problem, thanks. It was not obvious that this variable was being used at this stage

**Comment by woodser** [comment]
> It was not obvious that this variable was being used at this stage

I've improved the error message when JAVA_HOME isn't set. Thanks.
